MTVS-3rd-BanBanMooMani/MeMiLog

src/main/resources/view/404-page.html
src/main/resources/view/admin/post/postHidden.html
src/main/resources/view/admin/user/forgot-password.html
src/main/resources/view/admin/user/login.html
src/main/resources/view/admin/user/sign-up.html

admin page에서 Post Management의 Hidden Post page를 feature
** 추가로 adminLogin, adminSignUp, adminForgotPW page 업로드

feature PostMagement/HiddenPost&adminLogin&adminSignUp&adminForgotPW

---

src/main/resources/documentation/css/adminBoard.css
src/main/resources/view/admin/board/dailyTopicBoard.html
src/main/resources/view/admin/board/noticeBoard.html

오늘의 주제 수정 페이지 완성

---

src/main/resources/view/admin/report/reportTotal.html

Refactor: Report 페이지 수정

---

src/main/resources/documentation/css/home.css

refactor home.html

---

src/main/resources/view/admin/report/reportTotal.html
src/main/resources/view/admin/user/userBlackList.html

- BlackList Page 수정
- Report Page 수정

Refactor: 관리자 페이지 수정

---

src/main/resources/assets/libs/css/style.css

1. Ban Reason Button 색상 변경
<br>
<br>
<br>

Refactor: Ban Reason Button 수정

---

src/main/resources/documentation/css/adminBoard.css
src/main/resources/view/admin/board/noticeBoard.html

추후 여백 설정하여 보완 예정
1. 공지사항 테이블 페이지 제목 크기 조정
2. 공지사항 테이블 열 제목 위치 조정
3. 오늘의 주제 테이블 요소 간 간격 조정
<br>
<br>
<br>
> 여백 추가하여 레이아웃 보완 예정

관리자 페이지 내 공지사항, 오늘의 주제 작성 페이지 레이아웃 1차 수정

---

src/main/resources/static/document/css/forgot_password.css
src/main/resources/static/document/js/forgot_password.js
src/main/resources/templates/user/forgot_password.html

Refactor:  forgot_password 리팩토링

---

src/main/resources/static/document/css/allview.css
src/main/resources/templates/main/allview.html

1. allview 페이지 post modal 작성일, 감정 위치 변경 및 좋아요 수 추가

Fix: allview 페이지 post modal css 수정

---

src/main/resources/static/document/css/layout.css

1. 헤더 레이아웃 수정
2. body 좌우 여백 수정
<br>
> 페이지끼리 이동 했을 때에도 통일된 레이아웃으로 보일 수 있게 수정

헤더 레이아웃 수정, body 좌우 여백 수정

---

src/main/java/com/banbanmoomani/memilog/DTO/SelfUserDTO.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/resources/static/document/css/signup.css
src/main/resources/templates/user/signup.html

1. login, signup, forgot css 수정 : flex로 layout position 설정
2. SelfUserDTO 수정 : Getter&Setter 추가
3. jwt 폴더 생성
<br>
> MyBatis config 설정으로 DB와의 연결 & SpringSecurity 구현

Refactor : login, signup, forgot.css

---

src/main/java/com/banbanmoomani/memilog/config/UserConfig.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/resources/mapper/user-mapper.xml
src/main/resources/mybatis-config.xml

1. feature user-mapper.xml
2. refactor UserController, mybatis-config.xml
3. delete UserConfig.java
<br>
> "close #issue번호"로 해당 이슈 완료해주세요.
#71 -> Mapper 작성 완료
<br>
- MyBatis 연결

- feature user-mapper.xml

---

src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/PostDTO.java
src/main/java/com/banbanmoomani/memilog/controller/MainController.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/PostMapper.xml
src/main/resources/templates/main/postcreate.html

Feat:  post 타임리프 연동

---

src/main/java/com/banbanmoomani/memilog/controller/MainController.java

1. Main controller와 Post, Mydiary url 충돌 오류 해결
<br>
> "close #84 
<br>
<br>

MainController 수정(모호성 오류 수정)

---

src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/LoginRequestDTO.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/java/com/banbanmoomani/memilog/service/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/user/login.html
src/main/resources/templates/user/signup.html

1. user login 기능 구현
<br>
#71 
<br>
- user정보를 가져올 때 HttpSession에 key를 "user_id"로 해서 user_id값 가져온 후, UserMapper 통해서 findUserById로 가져올 수 있음
<br>
- userInfo modify 기능 구현

Feature: login기능

---

src/main/java/com/banbanmoomani/memilog/DTO/PostDTO.java
src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
src/main/resources/mapper/MydiaryMapper.xml

> 
1. alias 설정한 data들 mapper-resultMap의 column 이름 수정
2. 이미지 가져올 수 있게 PostDTO에 srcUrl field 추가
<br>
> "close #84
<br>
> alias 설정하면 column 이름도 맞춰야 하는데 아무 생각 없이 DB column 이름 짓는대로 수정해버렸네요,,,
<br>
> 일자별 데이터 가져오는 로직 추가 예정(찐)

post 조회 로직 수정

---

src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/PostMapper.xml
src/main/resources/templates/main/postcreate.html

Feat:  post 타임리프

---

src/main/java/com/banbanmoomani/memilog/service/user/RegisterMailService.java
src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
src/main/resources/mapper/UserMapper.xml

1. modifyUserInfo DAO를 동적 SQL이 되도록 refactoring
2. SMTP mail 본문 수정
<br>
#71 
<br>
- UserMapper로 잘 가져다 쓰시면 됩니다
<br>
- Done

Refactor: modifyUser -> dynamic SQL

---

src/main/java/com/banbanmoomani/memilog/DAO/MissionMapper.java
src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/MissionService.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/MissionMapper.xml
src/main/resources/mapper/PostMapper.xml

1. 해당 날짜에 작성한 글 불러오기 기능 구현 중
<br>
> #77

Feature: 날짜에 해당하는 게시물 조회

---

src/main/java/com/banbanmoomani/memilog/DTO/user/UserDTO.java
src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/main/mydiary.html

닉네임, 비밀번호 수정 기능 구현
<br>
> "close #84
<br>
> 회원 탈퇴 기능 구현

회원 정보(text only) 수정 기능 구현

---

src/main/java/com/banbanmoomani/memilog/DAO/AdminMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/admin/AdminDTO.java
src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
src/main/java/com/banbanmoomani/memilog/service/AdminService.java
src/main/resources/mapper/AdminMapper.xml

Feat: Admin Login

---

build.gradle
src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
src/main/resources/application.yml

1. 이미지 처리를 위해 GCP 설정 추가
2. MissionController에서 MissionDTO import 누락된 것 추가

이미지 파일 처리를 위해 GCP 설정 추가

---

.idea/gradle.xml
src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/PostMapper.xml
src/main/resources/templates/main/postupdate.html

Feat: Post Update,Delete 추가

---

src/main/java/com/banbanmoomani/memilog/DAO/AdminMapper.java
src/main/java/com/banbanmoomani/memilog/DAO/MeMiLogInfoMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/MeMiLogInfoDiff.java
src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
src/main/java/com/banbanmoomani/memilog/service/AdminService.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/mapper/MeMiLogInfoMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/admin/dashboard.html
src/main/resources/templates/admin/login.html
src/main/resources/templates/admin/reportTotal.html
src/main/resources/templates/admin/userBlackList.html

1. Header - 관리자 계정 정보
2. 로그아웃
3. 그래프 변화 수치 계산
<br>
> 이제 남은 건 신고 글 처리 뿐
<br>
> 신고 글 처리

Feat: Admin 페이지

---

.gitignore

.gitignore에 memilog-292b5416c430.json 파일 추가
<br>
> "close #84
<br>
>GCP json 파일 따로 전달 드리겠읍니다.
<br>

.gitignore 설정 수정

---

.gitignore
src/main/java/com/banbanmoomani/memilog/controller/FileController.java
src/main/java/com/banbanmoomani/memilog/service/FileService.java

GCP json 파일 변경
<br>
> "close #84
<br>
> 화이팅.....
<br>
> 화이팅........

json 파일 변경

---

src/main/java/com/banbanmoomani/memilog/config/StopWatchInterceptor.java
src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java

1. "/", "/user/**"를 제외하고 Interceptor 설정 해두었습니다
<br>
> "close #71 
<br>
- 다들 로그인 안했으면 로그인 페이지로 redirect해주는 예외처리 삭제해 주세요
<br>

Feature: Interceptor 추가

---

src/main/java/com/banbanmoomani/memilog/config/StopWatchInterceptor.java
src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java

1. Interceptor admin/login 페이지 제외
<br>
> "close #71
<br>
- session에 failMessage 값으로 메세지 넣어뒀습니다. 관련 html script 태그 달으셔서 alert 해주심 될 것 같습니다
<br>

Refactor: interceptor admin/login 페이지 제외

---

src/main/java/com/banbanmoomani/memilog/controller/FileController.java
src/main/java/com/banbanmoomani/memilog/service/FileService.java
src/main/resources/application.yml
src/main/resources/templates/main/mydiary.html

1. 프로필 사진 변경 기능 구현
1-1. 이전에 등록된 사진이 있으면 해당 사진 삭제하고 새로운 사진 url로 변경
1-2. 새로 올리는 프로필 사진 등록 기능 구현
<br>
> "close #84
<br>
> 기능 완성하고 설명 드리겠읍니다.
<br>
> 프로필 사진 삭제 기능 구현

프로필 사진 변경 기능 구현

---

src/main/resources/templates/main/postcreate.html
src/main/resources/templates/main/postupdate.html

1. post 뒤로가기 기능 추가
<br>
<br>
<br>

Feat: post back기능 추가

---

src/main/java/com/banbanmoomani/memilog/DAO/FileMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/FileDTO.java
src/main/java/com/banbanmoomani/memilog/DTO/post/CreateRequestDTO.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/FileService.java
src/main/resources/mapper/FileMapper.xml
src/main/resources/templates/main/postcreate.html

Feat: post 사진 추가

---

src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
src/main/resources/application.yml
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/main/mydiary.html

1. 사용자 탈퇴 기능 구현
<br>
> "close #84
<br>
> 회원 id를 세션에서 받아와 동적으로 user_id를 가지고 mydiary 내 정보 가져오기

사용자 탈퇴 기능 구현

---

src/main/java/com/banbanmoomani/memilog/DAO/MydiaryMapper.java
src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/java/com/banbanmoomani/memilog/service/MydiaryService.java
src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
src/main/resources/mapper/MydiaryMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/main/mydiary.html

1. 사용자 정보 조회 시 세션에서 user_id 값을 받아와 조회할 수 있게 수정
2. 프로필 사진이 등록되지 않은 경우 기본 이미지를 보여줄 수 있게 수정
3. 회원가입을 할 때 FILE 테이블에 user_id와 type(profile)도 등록해서 프로필 사진 기본값으로 보일 수 있게 수정
<br>
> "close #84
<br>
> 추후 회원가입 로직 테스트 필요
<br>
> 사용자 감정 통계 DB에서 데이터 받아올 수 있게 수정

회원 정보 동적으로 불러올 수 있게 수정

---

src/main/resources/static/document/css/layout.css
src/main/resources/templates/fragments/mainHeader.html

1. 세션에서 user_id 존재 여부 확인
2. 확인 후 user_id가 존재할 경우 [로그아웃] 버튼으로 변경
3. [로그아웃] 버튼 클릭 시 /user/deleteSession 으로 이동
<br>
> #136

로그인 성공 시 로그인 버튼 > 로그아웃 버튼으로 변경

---

src/main/java/com/banbanmoomani/memilog/DAO/LikeMapper.java
src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/LikeDTO.java
src/main/java/com/banbanmoomani/memilog/MeMiLogApplication.java
src/main/java/com/banbanmoomani/memilog/config/MailConfig.java
src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/LikeMapper.xml
src/main/resources/mapper/PostMapper.xml

1. Like, disLike 기능 구현
<br>
> "close #139 
<br>
<br>

Feature: like 기능 구현 - Controller, Service, Mapper

---

src/main/resources/static/document/js/missionPost.js

1. fetch함수 likeFetch(), dislikeFetch() 구현 - missionPost.js
<br>
> "close #139 
<br>
- missionPost.js에 들어가 있으니 post_id값 html에서 잘 받아와서 넘기시면 됩니다.
- 주석 처리 해뒀으니 잘 하실 거라 믿습니다
<br>

Feature: 좋아요, 싫어요 Fetch함수 구현

---

src/main/java/com/banbanmoomani/memilog/controller/UserController.java

Feat/User 정지 회원 로그인 거부

---

src/main/java/com/banbanmoomani/memilog/controller/MainController.java
src/main/resources/mapper/PostMapper.xml
src/main/resources/templates/main/home.html

1. post 넘기는 기능 추가
2. 아카이브 랜덤 기능 추가
<br>
<br>
<br>

Feat: post 사진 넘기는 기능, 아카이브 랜덤 기능 추가

---

src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/resources/mapper/PostMapper.xml

Feat: post 경로 설정

---

src/main/resources/static/document/css/mydiary.css
src/main/resources/templates/main/mydiary.html

mydiary 모아보기 컨테이너 무한스크롤 구현
<br>
> "close #84
<br>
> 이제 진짜 클릭하면 게시글 상세 정보 확인하고 수정/삭제 가능하게 구현하기...

mydiary 모아보기 컨테이너 무한스크롤 구현

---

src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/postview.css

Refactor: 사진 크기 고정

---

src/main/java/com/banbanmoomani/memilog/DAO/ReportBoardMapper.java
src/main/java/com/banbanmoomani/memilog/service/AdminService.java
src/main/resources/mapper/ReportBoardMapper.xml

1. 신고 글 처리 시 유저 정지 일수 계산 로직이 필요할 때 쉽게 넣기 위해 sql 로직 변경
<br>
<br>
<br>

Refactor: 신고 글 처리 - 유저 정지 일수 서비스 로직 추가

---

src/main/resources/static/document/css/mydiary.css

1. MyDiary Modal z-index header 보다 높게 수정
<br>
<br>
<br>

Refactor/inuk MyDiary

---

src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/UpdateFileDTO.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/MissionMapper.xml
src/main/resources/mapper/PostMapper.xml
src/main/resources/templates/main/home.html
src/main/resources/templates/main/postupdate.html

Feat: post 수정

---

src/main/resources/static/document/css/layout.css
src/main/resources/static/document/css/mydiary.css
src/main/resources/templates/main/mydiary.html

1. 폰트 수정(헤더와 컨테이너 영역 다르게)
2. 윈도우 크롬에 맞춰 전체적인 레이아웃 수정
3. post-card-container와 date-selector의 스크롤바 숨기기
<br>
> "close #158
<br>
> 로그인/회원가입 페이지 레이아웃 수정

mydiary CSS 수정

---

src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/ImageOrderDTO.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/PostMapper.xml
src/main/resources/static/document/css/home.css
src/main/resources/static/document/js/post.js
src/main/resources/templates/main/home.html
src/main/resources/templates/main/postupdate.html

1. 버튼 고정 기능
2. post 타임리프 연동
<br>
<br>
<br>

Feat: 저장된 post 데이터 타임리프 연동

---

src/main/java/com/banbanmoomani/memilog/DAO/MissionMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/MainTitleDTO.java
src/main/java/com/banbanmoomani/memilog/controller/MainController.java
src/main/java/com/banbanmoomani/memilog/service/MissionService.java
src/main/resources/mapper/MissionMapper.xml
src/main/resources/templates/main/home.html

1. MainTitleDTO 생성
2. MainTitle Banner 이미지 연동
3. 날짜 연동
<br>
<br>
<br>

Refactor/inuk Main Title

---

src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/layout.css
src/main/resources/templates/main/home.html

메인 페이지 레이아웃 수정
<br>
> "close #158
<br>

메인 레이아웃 재수정

---

src/main/resources/static/document/js/post.js
src/main/resources/templates/main/postcreate.html

1. emotion js 수정
<br>
<br>
<br>

refactor: emotion js 수정

---

src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
src/main/java/com/banbanmoomani/memilog/service/FileService.java
src/main/resources/application.yml
src/main/resources/templates/main/home.html

1. FileService : FileInputStream을 InputStream inputStream = getClass().getResourceAsStream("/memilog-4ed085e451cd.json");로 변경
2. application.yml에서 thymeleaf.prefix를 classpath:/templates/로 하기
<br>
<br>
- 다들 타임리프 @{}로 가져올 때 /로 시작하지 말아주세요
<br>

Feature: .jar 파일 배포를 위한 application.yml 및 경로 수정

---

src/main/resources/static/document/css/allview.css
src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/layout.css
src/main/resources/static/document/css/mydiary.css
src/main/resources/static/document/css/postview.css
src/main/resources/static/document/css/searchbar.css
src/main/resources/static/document/js/missionPost.js
src/main/resources/templates/fragments/mainHeader.html

1. search box 레이아웃, 검색 버튼 이미지 수정
2. 폰트 수정
3. postview layout 수정
<br>
> "close #158
<br>

allview layout 수정

---

src/main/resources/templates/admin/dailyTopicBoard.html

1. Refactor: 미션 수정 시 태그 문제 해결
<br>
기능 테스트

Refactor: 미션 수정시 태그 문제 해결

---

src/main/resources/static/document/css/postview.css
src/main/resources/templates/main/postview.html

상세보기 모달 내 이미지, 폰트 종류, 크기 및 위치 조정
<br>
> "close #158 
<br>

게시물 상세보기 모달 수정

---

src/main/resources/static/document/css/layout.css
src/main/resources/static/document/css/post.css
src/main/resources/templates/fragments/mainHeader.html
src/main/resources/templates/main/postcreate.html

게시글 작성화면 폰트, 레이아웃 등 수정
<br>
> "close #158
<br>

게시글 작성 화면 CSS 수정

---

src/main/resources/static/document/css/postview.css

신고 모달 레이아웃 수정
<br>
> "close #158
<br>

신고 모달 레이아웃 수정

---

src/main/resources/mapper/MydiaryMapper.xml
src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/mydiary.css
src/main/resources/static/document/css/postview.css
src/main/resources/static/document/js/mydiary.js
src/main/resources/templates/main/home.html
src/main/resources/templates/main/mydiary.html

mydiary page에서 사진 클릭 시 상세보기 모달 열리는 기능 추가
<br>
> "close #84
<br>
> 모달에서 수정, 삭제 버튼 누르면 게시글 수정 페이지 이동/게시글 삭제 작동하는 로직 추가

mydiary page에서 사진 클릭 시 상세보기 모달 열리는 기능 추가

---

src/main/java/com/banbanmoomani/memilog/DAO/LikeMapper.java
src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/DTO/LikeDTO.java
src/main/java/com/banbanmoomani/memilog/DTO/mydiary/PostRequestDTO.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/FileMapper.xml
src/main/resources/mapper/LikeMapper.xml
src/main/resources/mapper/PostMapper.xml
src/main/resources/static/document/js/allviewModal.js
src/main/resources/static/document/js/missionPost.js
src/main/resources/templates/main/postview.html

1. 좋아요, 좋아요 취소 기능 연결
<br>
> #77

Fix: 좋아요, 좋아요 취소 기능

---

src/main/resources/mapper/MydiaryMapper.xml
src/main/resources/static/document/css/mydiary.css
src/main/resources/static/document/js/mydiary.js

1. 게시글 조회 시 정렬 기준 작성일로 수정
2. 게시글 상세보기 모달에서 수정, 삭제 기능 추가
<br>
> "close #84
<br>
> like 수 받아오기

게시글 상세보기 모달에서 수정, 삭제 기능 추가

---

src/main/resources/templates/main/home.html

Feat: 삭제 부분 리로드추가

---

src/main/resources/templates/main/home.html

Reverts MTVS-3rd-BanBanMooMani/MeMiLog#188

Revert "Feat: 삭제 부분 리로드추가"

---

src/main/resources/templates/main/home.html

1. 삭제부분 리로드 추가 merge
<br>
<br>
<br>

Feat: Feat: 삭제 부분 리로드추가 merge

---

src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/java/com/banbanmoomani/memilog/service/PostService.java
src/main/resources/mapper/PostMapper.xml

1. post작성 그 날 미션에 대해 작성 1개 고정
<br>
<br>
<br>

Feat: post 작성 1개 기능 추가

---

src/main/resources/mapper/PostMapper.xml

Feat: 충돌 해결

---

src/main/resources/templates/main/allview.html

Fix: 테마 카테고리 수정

---

src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/layout.css
src/main/resources/templates/main/home.html
src/main/resources/templates/main/mydiary.html

회원 가입 시 사용자 프로필 사진 기본값으로 설정하는 로직 추가
> "close #71 
<br>

회원 가입 로직 수정

---

src/main/resources/static/document/css/allview.css
src/main/resources/static/document/css/home.css
src/main/resources/static/document/css/layout.css
src/main/resources/static/document/css/mydiary.css
src/main/resources/templates/main/home.html
src/main/resources/templates/main/mydiary.html

allView memo 가로 패딩 추가
<br>
> "close #158 
<br>

allView memo 레이아웃 수정

---

src/main/java/com/banbanmoomani/memilog/controller/PostController.java
src/main/resources/static/document/css/postview.css
src/main/resources/templates/main/allview.html

1. 테마 조회 버튼 돋보기 모양으로 수정
2. 폴라로이드 게시물 닉네임 css 수정
<br>
> #77

Fix: 테마 조회 버튼 수정, 폴라로이드 닉네임 css 수정

---

src/main/resources/static/document/js/allviewModal.js

1. 미션 게시글 페이지 수정 연결
<br>
<br>
<br>

Refactor: 미션 상세 페이지 리팩토링

---

src/main/java/com/banbanmoomani/memilog/controller/UserController.java
src/main/resources/static/document/js/home.js

1. 로그인 해야 포스트 상세보게 리팩토링 함
<br>
<br>
<br>

Refactor: 로그인 시 모달 창 나오게 리팩토링

---

src/main/java/com/banbanmoomani/memilog/controller/PostController.java

1. 포스트 생성, 수정 저장 경로 변경
<br>
<br>
<br>

Refactor: 포스트 생성 후 경로 변경

---

src/main/java/com/banbanmoomani/memilog/DAO/MeMiLogInfoMapper.java
src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
src/main/java/com/banbanmoomani/memilog/service/AdminService.java
src/main/resources/mapper/DashBoardMapper.xml

1. 변경 사항 1
2. 변경 사항 2
3. ...
<br>
<br>
<br>

Refactor: Admin DashBoard
